using System.Diagnostics;
using System.Net;
using System.Net.Http.Json;
using System.Net.Sockets;
using System.Text;
using System.Text.Json;
using Honua.Console.Contracts;
using Honua.Console.Shell.Pages;
using Honua.Console.Shell.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Testcontainers.PostgreSql;

namespace Honua.Console.Native.Core.Tests;

public sealed class OperateTransitionLiveServerTests
{
    private const string RunLiveServerTestsVariable = "HONUA_CONSOLE_RUN_LIVE_SERVER_TESTS";
    private const string HonuaServerProjectVariable = "HONUA_SERVER_PROJECT";
    private const string HonuaServerStartupTimeoutVariable = "HONUA_CONSOLE_LIVE_SERVER_STARTUP_TIMEOUT_SECONDS";
    private const string DefaultHonuaServerProject =
        "/home/makani/honua-server/src/Honua.Server/Honua.Server.csproj";

    [SkippableFact]
    [Trait("Category", "Integration")]
    public async Task OperateConnectionsSurfaceRendersFromLiveHonuaServerData()
    {
        if (!string.Equals(
                Environment.GetEnvironmentVariable(RunLiveServerTestsVariable),
                "true",
                StringComparison.OrdinalIgnoreCase))
        {
            Skip.If(true, $"Set {RunLiveServerTestsVariable}=true to run the live honua-server Testcontainers integration test.");
        }

        var serverProject = Environment.GetEnvironmentVariable(HonuaServerProjectVariable);
        if (string.IsNullOrWhiteSpace(serverProject))
        {
            serverProject = DefaultHonuaServerProject;
        }

        if (!File.Exists(serverProject))
        {
            Skip.If(true, $"honua-server project was not found at '{serverProject}'. Set {HonuaServerProjectVariable} to a Honua.Server.csproj path.");
        }

        await using var postgres = new PostgreSqlBuilder("postgis/postgis:17-3.5-alpine")
            .WithDatabase("honua_console_operate")
            .WithUsername("honua_user")
            .WithPassword("honua_password")
            .Build();

        try
        {
            await postgres.StartAsync();
        }
        catch (Exception ex) when (LooksLikeDockerUnavailable(ex))
        {
            Skip.If(true, $"Docker is unavailable for Testcontainers: {ex.Message}");
        }

        await postgres.ExecScriptAsync("""
            CREATE EXTENSION IF NOT EXISTS postgis;
            CREATE SCHEMA IF NOT EXISTS console_live;
            DROP TABLE IF EXISTS console_live.operate_fixture;
            CREATE TABLE console_live.operate_fixture (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name text NOT NULL,
                geom geometry(Point, 4326) NOT NULL
            );
            INSERT INTO console_live.operate_fixture (name, geom)
            VALUES ('console live fixture', ST_SetSRID(ST_MakePoint(-157.8583, 21.3069), 4326));
            """);

        using var server = await HonuaServerProcess.StartAsync(serverProject, postgres.GetConnectionString());
        using var adminClient = new HttpClient { BaseAddress = server.BaseUri };

        var connectionId = await CreateConnectionAsync(adminClient, postgres);
        await PublishLayerAsync(adminClient, connectionId);

        var operateClient = new HonuaAdminOperateHttpClient(
            new HttpClient { BaseAddress = server.BaseUri },
            new HonuaAdminOperateClientOptions(server.BaseUri));
        var dataSource = new HonuaServerOperateTransitionDataSource(operateClient);

        var liveServiceCount = await GetLiveServiceCountAsync(adminClient);

        var connectionsHtml = await RenderPageAsync<OperateConnectionsPage>(dataSource);
        var resourcesHtml = await RenderPageAsync<OperateResourcesPage>(dataSource);
        var servicesHtml = await RenderPageAsync<OperateServicesPage>(dataSource);
        var layersHtml = await RenderPageAsync<OperateLayersPage>(dataSource);
        var settingsHtml = await RenderPageAsync<OperateSettingsPage>(dataSource);

        // Connections and resources render the live connection and the published layer.
        Assert.Contains("Console Live PostGIS", connectionsHtml, StringComparison.Ordinal);
        Assert.Contains("Console Live Fixture", resourcesHtml, StringComparison.Ordinal);
        Assert.Contains("console_live", resourcesHtml, StringComparison.Ordinal);

        // Services, layers, and settings slices render their operate surface end to end against the
        // same live honua-server fixture.
        Assert.Contains("Services And Layers", servicesHtml, StringComparison.Ordinal);
        Assert.Contains("Operate / Layers", layersHtml, StringComparison.Ordinal);
        Assert.Contains("Operator Settings", settingsHtml, StringComparison.Ordinal);

        // The settings slice always reflects live server metadata read from GET /api/v1/admin/version.
        Assert.Contains("Admin API version", settingsHtml, StringComparison.Ordinal);

        // When the Metadata v2 graph projects the published service, the services and layers surfaces
        // render the live published layer; otherwise they render the shared empty operate surface
        // rather than fabricated rows. Branching on the live services count keeps the assertion
        // deterministic against either projection outcome.
        if (liveServiceCount > 0)
        {
            Assert.Contains("Console Live Fixture", servicesHtml, StringComparison.Ordinal);
            Assert.Contains("Console Live Fixture", layersHtml, StringComparison.Ordinal);
        }
    }

    private static async Task<int> GetLiveServiceCountAsync(HttpClient client)
    {
        using var response = await client.GetAsync("/api/v1/admin/services/").ConfigureAwait(false);
        response.EnsureSuccessStatusCode();
        await using var stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
        using var json = await JsonDocument.ParseAsync(stream).ConfigureAwait(false);
        return json.RootElement.TryGetProperty("data", out var data) && data.ValueKind == JsonValueKind.Array
            ? data.GetArrayLength()
            : 0;
    }

    private static async Task<Guid> CreateConnectionAsync(HttpClient client, PostgreSqlContainer postgres)
    {
        var response = await client.PostAsJsonAsync(
                "/api/v1/admin/connections/",
                new
                {
                    name = "Console Live PostGIS",
                    host = postgres.Hostname,
                    port = postgres.GetMappedPublicPort(5432),
                    databaseName = "honua_console_operate",
                    username = "honua_user",
                    password = "honua_password",
                    sslRequired = false,
                    sslMode = "Disable"
                })
            .ConfigureAwait(false);
        response.EnsureSuccessStatusCode();

        await using var stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
        using var json = await JsonDocument.ParseAsync(stream).ConfigureAwait(false);
        return json.RootElement.GetProperty("data").GetProperty("connectionId").GetGuid();
    }

    private static async Task PublishLayerAsync(HttpClient client, Guid connectionId)
    {
        var response = await client.PostAsJsonAsync(
                $"/api/v1/admin/connections/{connectionId:D}/layers/",
                new
                {
                    schema = "console_live",
                    table = "operate_fixture",
                    layerName = "Console Live Fixture",
                    description = "Live Testcontainers Operate fixture",
                    geometryColumn = "geom",
                    geometryType = "Point",
                    primaryKey = "id",
                    serviceName = "default",
                    enabled = true
                })
            .ConfigureAwait(false);
        response.EnsureSuccessStatusCode();
    }

    private static async Task<string> RenderPageAsync<TComponent>(IOperateTransitionDataSource dataSource)
        where TComponent : IComponent
    {
        var services = new ServiceCollection();
        services.AddSingleton<ILoggerFactory>(NullLoggerFactory.Instance);
        services.AddSingleton(dataSource);
        await using var serviceProvider = services.BuildServiceProvider();
        var loggerFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
        await using var renderer = new HtmlRenderer(serviceProvider, loggerFactory);

        return await renderer.Dispatcher.InvokeAsync(async () =>
        {
            var output = await renderer.RenderComponentAsync<TComponent>(ParameterView.Empty);
            return output.ToHtmlString();
        }).ConfigureAwait(false);
    }

    private static bool LooksLikeDockerUnavailable(Exception ex)
    {
        var text = ex.ToString();
        return text.Contains("Docker", StringComparison.OrdinalIgnoreCase)
            || text.Contains("docker", StringComparison.OrdinalIgnoreCase)
            || text.Contains("daemon", StringComparison.OrdinalIgnoreCase)
            || text.Contains("NamedPipe", StringComparison.OrdinalIgnoreCase)
            || text.Contains("/var/run/docker.sock", StringComparison.OrdinalIgnoreCase);
    }

    private sealed class HonuaServerProcess : IDisposable
    {
        private readonly Process _process;
        private readonly StringBuilder _output;

        private HonuaServerProcess(Process process, Uri baseUri, StringBuilder output)
        {
            _process = process;
            BaseUri = baseUri;
            _output = output;
        }

        public Uri BaseUri { get; }

        public static async Task<HonuaServerProcess> StartAsync(
            string projectPath,
            string connectionString)
        {
            var port = GetAvailableTcpPort();
            var baseUri = new Uri($"http://127.0.0.1:{port.ToString(System.Globalization.CultureInfo.InvariantCulture)}");
            var output = new StringBuilder();
            var process = new Process
            {
                StartInfo = new ProcessStartInfo("dotnet")
                {
                    WorkingDirectory = Path.GetDirectoryName(projectPath)!,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false
                },
                EnableRaisingEvents = true
            };

            process.StartInfo.ArgumentList.Add("run");
            process.StartInfo.ArgumentList.Add("--project");
            process.StartInfo.ArgumentList.Add(projectPath);
            process.StartInfo.ArgumentList.Add("--no-launch-profile");
            process.StartInfo.ArgumentList.Add("--no-restore");
            process.StartInfo.Environment["ASPNETCORE_ENVIRONMENT"] = "Test";
            process.StartInfo.Environment["HONUA_REGISTER_TEST_INFRASTRUCTURE"] = "true";
            process.StartInfo.Environment["ASPNETCORE_URLS"] = baseUri.ToString();
            process.StartInfo.Environment["ConnectionStrings__honua"] = connectionString;
            process.StartInfo.Environment["ConnectionStrings__DefaultConnection"] = connectionString;
            process.StartInfo.Environment["DataSource__Provider"] = "postgres";
            process.StartInfo.Environment["HONUA_DEV_AUTH"] = "true";
            process.StartInfo.Environment["HONUA_DEV_AUTH_ALLOW_BYPASS"] = "true";
            process.StartInfo.Environment["Geocoding__Nominatim__BaseUrl"] = "https://8.8.8.8/nominatim";
            process.StartInfo.Environment["Geocoding__Providers__Nominatim__BaseUrl"] = "https://8.8.8.8/nominatim";
            process.StartInfo.Environment["Security__ConnectionEncryption__MasterKey"] =
                "console-live-test-master-key-32-bytes";
            process.StartInfo.Environment["HONUA_OBSERVABILITY"] = "false";

            process.OutputDataReceived += (_, args) => AppendOutput(output, args.Data);
            process.ErrorDataReceived += (_, args) => AppendOutput(output, args.Data);

            if (!process.Start())
            {
                throw new InvalidOperationException("Failed to start honua-server process.");
            }

            process.BeginOutputReadLine();
            process.BeginErrorReadLine();

            var server = new HonuaServerProcess(process, baseUri, output);
            try
            {
                await server.WaitForHealthAsync().ConfigureAwait(false);
                return server;
            }
            catch
            {
                server.Dispose();
                throw;
            }
        }

        public void Dispose()
        {
            try
            {
                if (!_process.HasExited)
                {
                    _process.Kill(entireProcessTree: true);
                }
            }
            finally
            {
                _process.Dispose();
            }
        }

        private async Task WaitForHealthAsync()
        {
            using var client = new HttpClient { BaseAddress = BaseUri };
            var timeout = GetStartupTimeout();
            var deadline = DateTimeOffset.UtcNow.Add(timeout);
            while (DateTimeOffset.UtcNow < deadline)
            {
                if (_process.HasExited)
                {
                    throw new InvalidOperationException(
                        $"honua-server exited with code {_process.ExitCode}.{Environment.NewLine}{GetCapturedOutput()}");
                }

                try
                {
                    using var response = await client.GetAsync("/healthz/live").ConfigureAwait(false);
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        return;
                    }
                }
                catch (HttpRequestException)
                {
                }

                await Task.Delay(TimeSpan.FromSeconds(1)).ConfigureAwait(false);
            }

            throw new TimeoutException(
                $"honua-server did not become healthy at {BaseUri} within {timeout.TotalSeconds.ToString(System.Globalization.CultureInfo.InvariantCulture)} seconds.{Environment.NewLine}{GetCapturedOutput()}");
        }

        private static TimeSpan GetStartupTimeout()
        {
            var configured = Environment.GetEnvironmentVariable(HonuaServerStartupTimeoutVariable);
            return int.TryParse(configured, out var seconds) && seconds > 0
                ? TimeSpan.FromSeconds(seconds)
                : TimeSpan.FromSeconds(300);
        }

        private static int GetAvailableTcpPort()
        {
            var listener = new TcpListener(IPAddress.Loopback, 0);
            listener.Start();
            var port = ((IPEndPoint)listener.LocalEndpoint).Port;
            listener.Stop();
            return port;
        }

        private static void AppendOutput(StringBuilder output, string? line)
        {
            if (!string.IsNullOrWhiteSpace(line))
            {
                output.AppendLine(line);
            }
        }

        private string GetCapturedOutput() =>
            _output.Length == 0 ? "No honua-server output was captured." : _output.ToString();
    }
}
