/**
 * Saved web maps — TypeScript types.
 *
 * `ContentItem` mirrors `schemas/content-item-v1.json` (projection of #10).
 * `WebMapDoc` mirrors `schemas/webmap-doc-v1.json` (authored by #14).
 *
 * Generated by hand to keep #14 unblocked. When #10 ships canonical generated
 * types via `json-schema-to-typescript`, switch to the generated module and
 * delete the hand-rolled shapes here.
 */

import type { ServiceLink } from "../contracts/content-item.js";

export type ContentItemType = "service" | "layer" | "map" | "scene" | "app" | "document" | "external-url";

export type SharingLevel = "private" | "org" | "group" | "public-link" | "public";

export interface ContentOwner {
  id: string;
  name: string;
  kind: "user" | "org" | "group";
}

export interface ContentTimestamps {
  created: string;
  modified: string;
  published: string | null;
  refreshed: string | null;
  deleted?: string | null;
}

export interface ContentExtent {
  bbox: [number, number, number, number];
  crs: "EPSG:4326";
}

export interface ContentLicense {
  spdx: string | null;
  name: string;
  url: string | null;
}

export type SourceKind = "import" | "publish" | "admin-job" | "external" | "manual";

export type HistoryEventKind =
  | "import"
  | "publish"
  | "admin-job"
  | "external"
  | "manual"
  | "update"
  | "share-change"
  | "metadata-edit";

export interface ContentSourceHistoryEvent {
  at: string;
  kind: HistoryEventKind;
  actor: string;
}

export interface ContentSource {
  kind: SourceKind;
  sourceId: string | null;
  jobId: string | null;
  publishedBy: string | null;
  history: ContentSourceHistoryEvent[];
}

export interface ContentEndpoints {
  self: ServiceLink;
  geoservices: ServiceLink | null;
  ogcFeatures: ServiceLink | null;
  stac: ServiceLink | null;
  tiles: ServiceLink | null;
}

export interface ContentPreview {
  thumbnail: string | null;
  image: string | null;
}

export interface ContentDependency {
  id: string;
  type: ContentItemType;
  role: string;
}

export interface ContentAccess {
  sharing: SharingLevel;
  embeddable: boolean;
  openData: boolean;
}

export interface MapTarget {
  type: "map";
  webmapJsonRef: string;
  operationalLayerCount: number;
}

export interface ContentItem<TTarget = unknown> {
  id: string;
  slug: string | null;
  type: ContentItemType;
  title: string;
  summary: string;
  description: string;
  tags: string[];
  owner: ContentOwner;
  timestamps: ContentTimestamps;
  extent: ContentExtent | null;
  nativeCrs: string | null;
  license: ContentLicense;
  attribution: string | null;
  source: ContentSource;
  target: TTarget;
  endpoints: ContentEndpoints;
  preview: ContentPreview;
  capabilities: string[];
  dependencies: ContentDependency[];
  access: ContentAccess;
  extensions: Record<string, Record<string, unknown>>;
}

/** A saved web map is a `ContentItem` with `type: "map"` and a `MapTarget`. */
export type SavedMapItem = ContentItem<MapTarget> & { type: "map" };

// ── WebMap document (durable saved-map state) ──────────────────────────────

export const WEBMAP_DOC_VERSION = "honua-webmap/v1" as const;
export type WebMapDocVersion = typeof WEBMAP_DOC_VERSION;

export const ANNOTATION_WORKSPACE_VERSION = "honua-annotations/v1" as const;
export type AnnotationWorkspaceVersion = typeof ANNOTATION_WORKSPACE_VERSION;

export type OperationalLayerType =
  | "honua-feature"
  | "honua-vector-tile"
  | "honua-raster-tile"
  | "honua-image"
  | "ogc-features"
  | "ogc-tiles"
  | "geojson"
  | "wms"
  | "wmts"
  | "unsupported";

export interface SourceRef {
  itemId: string;
  subLayerId?: string | null;
}

export type SavedStyleOrigin = "admin-layer-style" | "portal-override";

export interface StyleRef {
  itemId?: string;
  inline?: Record<string, unknown> | null;
  /**
   * Identifies ownership of the effective style. `admin-layer-style` means
   * the portal is referencing a server/admin authored style item. A
   * `portal-override` is saved on the WebMapDoc and must not mutate the
   * authoritative server/admin style.
   */
  origin?: SavedStyleOrigin;
}

export interface OperationalLayer {
  id: string;
  title: string;
  layerType: OperationalLayerType;
  sourceRef: SourceRef;
  styleRef?: StyleRef | null;
  visibility: boolean;
  opacity: number;
  popupInfo?: Record<string, unknown> | null;
  minScale?: number | null;
  maxScale?: number | null;
}

export type BaseMapLayerType = "honua-vector-tile" | "honua-raster-tile" | "wmts" | "xyz" | "style-url";

export interface BaseMapLayer {
  id: string;
  title?: string;
  layerType: BaseMapLayerType;
  sourceRef?: { itemId: string } | null;
  styleUrl?: string | null;
  visibility?: boolean;
  opacity?: number;
}

export interface BaseMap {
  title: string;
  baseMapLayers: BaseMapLayer[];
}

export interface ViewpointExtent {
  xmin: number;
  ymin: number;
  xmax: number;
  ymax: number;
  spatialReference?: { wkid?: number; latestWkid?: number };
}

export interface InitialState {
  viewpoint: { extent: ViewpointExtent; rotation?: number };
}

export interface AnnotationWorkspaceVisibility {
  /**
   * Annotation visibility follows the saved map's sharing policy. Public
   * comment authoring is an explicit owner-controlled opt-in for shared maps.
   */
  defaultAudience: "map";
  publicComments: boolean;
}

export interface AnnotationWorkspaceState {
  version: AnnotationWorkspaceVersion;
  visibility: AnnotationWorkspaceVisibility;
  annotationSets: Record<string, unknown>[];
  commentThreads: Record<string, unknown>[];
}

export interface WebMapDoc {
  version: WebMapDocVersion;
  authoringApp?: string;
  authoringAppVersion?: string;
  operationalLayers: OperationalLayer[];
  baseMap: BaseMap;
  initialState: InitialState;
  spatialReference?: { wkid?: number; latestWkid?: number };
  annotations?: AnnotationWorkspaceState;
}

// ── Viewer state (stub — final shape lands with #13) ────────────────────────
//
// `ViewerState` is the in-memory shape produced by the #13 viewer. The
// serializer treats it as the source of truth for the durable `WebMapDoc`.
// Field names are chosen to align with the `WebMapDoc` schema so the mapping
// stays trivial. When #13 lands, this interface should be re-exported from
// the viewer module rather than duplicated here.

export interface ViewerLayerState {
  id: string;
  title: string;
  layerType: OperationalLayerType;
  sourceRef: SourceRef;
  styleRef?: StyleRef | null;
  visibility: boolean;
  opacity: number;
  popupInfo?: Record<string, unknown> | null;
  minScale?: number | null;
  maxScale?: number | null;
}

export interface ViewerBaseMapState {
  title: string;
  baseMapLayers: BaseMapLayer[];
}

export interface ViewerExtentState {
  xmin: number;
  ymin: number;
  xmax: number;
  ymax: number;
  rotation?: number;
}

export interface ViewerState {
  /** Layer order is the array order, top-most last (MapLibre convention). */
  operationalLayers: ViewerLayerState[];
  baseMap: ViewerBaseMapState;
  extent: ViewerExtentState;
  annotations?: AnnotationWorkspaceState;
}

// ── Action inputs ──────────────────────────────────────────────────────────

export interface SaveMapInput {
  title: string;
  summary?: string | null;
  tags?: string[];
  sharing?: SharingLevel;
  state: ViewerState;
  thumbnail?: Blob | null;
}

export interface DuplicateMapInput {
  /** Source item id. */
  fromId: string;
  /** Optional override; defaults to "<source title> (copy)". */
  title?: string;
}

export interface RenameMapInput {
  id: string;
  title?: string;
  summary?: string | null;
  tags?: string[];
}

// ── Surface taxonomy (mirrors #10's `missing | unauthorized | unsupported`) ─

export type LoadSurface =
  | { kind: "ok"; item: SavedMapItem; doc: WebMapDoc }
  | { kind: "missing"; id: string }
  | { kind: "unauthorized"; id: string }
  | { kind: "unsupported"; id: string; reason: string };
