name: Security

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read
  security-events: write
  id-token: write
  actions: read

jobs:
  trivy:
    uses: honua-io/.github/.github/workflows/reusable-trivy.yml@aebfacd3f3c6b551fa9bf703501c0a12a050faf3 # main
    with:
      scan-type: fs

  scorecard:
    uses: honua-io/.github/.github/workflows/reusable-scorecard.yml@aebfacd3f3c6b551fa9bf703501c0a12a050faf3 # main
